# SPDX-License-Identifier: Apache-2.0
version: "2.1"

volumes:
  pgdata:
  walletstore:

networks:
  property-registration-network.com:
    external:
      name: network_registration

services:
  explorerdb.property-registration-network.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.property-registration-network.com
    hostname: explorerdb.property-registration-network.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 100s
      timeout: 100s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - property-registration-network.com

  explorer.property-registration-network.com:
    image: hyperledger/explorer:latest
    container_name: explorer.property-registration-network.com
    hostname: explorer.property-registration-network.com
    environment:
      - DATABASE_HOST=explorerdb.property-registration-network.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=true
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./property-registration-network.json:/opt/explorer/app/platform/fabric/property-registration-network.json
      - ./crypto-config/organizations:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.property-registration-network.com:
        condition: service_healthy
    networks:
      - property-registration-network.com
